export const dataSet = [
  {
    id: 1,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "booked",
  },
  {
    id: 2,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "abandoned",
  },
  {
    id: 3,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "booked",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
];
