export const dataSet = [
  {
    id: 1,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "booked",
  },
  {
    id: 2,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "abandoned",
  },
  {
    id: 3,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "booked",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
  {
    id: 4,
    start: Date.now().toString(),
    return: Date.now().toString(),
    vehicleId: "MB3456788",
    customer: "Ogechi Helen",
    phone: `(+234) 7065432953`,
    email: `sample@gmail.com`,
    status: "cancelled",
  },
];


export const dashboardTempData = [
  {
    name: "CUSTOMERS STATISTIC",
    url: "/dashboard/customers",
    Totalbooking: 150,
    box: [
      {
        name: "verified",
        total: 100,
      },
      {
        name: "unverified",
        total: 50,
      },
    ],
  },
  {
    name: "CAR BOOKINGS STATISTIC",
    url: "/dashboard/bookings",
    Totalbooking: 100,
    box: [
      {
        name: "Booked",
        total: 50,
      },
      {
        name: "pending",
        total: 30,
      },
      {
        name: "cancelled",
        total: 20,
      },
    ],
  },
]